### ISSUE TITLE
/cmregister getting segfaulted

### ISSUE THREAD

**Issue by ineedblood** [erfg12/clanmod-jka#15]
I was checking the /commands printf on the source and tried running /cmregister which caused a segfault on the server

Tried commands 

/cmregister
/cmregister aaa 
/cmregister aaa aaa 

```
Sending heartbeat to masterjk3.ravensoft.com
Sending heartbeat to master.jkhub.org
ClientBegin: 0
Segmentation fault (core dumped)
```

I'm considering removing them from the commands printf since it would allow users to crash the server at will

**Comment by erfg12** [comment]
do you have clanmod.db file next to your server hosting software?

**Comment by ineedblood** [comment]
@erfg12 clanmod.db is present, tried with a debug build of ojkded but it drops segfault without any other information

**Comment by erfg12** [comment]
In the "void sqliteRegisterUser(char *SQLStmnt, ...) {" function there's a line that says...

    if (rc) //error connecting
        sqlite3_close(db);

Try chaning it to:

    if (rc != SQLITE_OK) { //error connecting
        sqlite3_close(db);
        return;
    }

**Comment by erfg12** [comment]
This is an issue due to the cleanName function. Remove this function completely and use Q_CleanStr instead.

**Comment by ineedblood** [comment]
Thought it was fixed with https://github.com/erfg12/clanmod-jka/commit/b744c782cb14269f0f1381d8278a40bafe80cee0 but propagated to cmlogin
```bash
Program received signal SIGSEGV, Segmentation fault.
0xb7c50383 in _IO_vfprintf_internal (s=0xbfff03a0, format=<optimized out>, ap=0xbfff08a8 "\300\062}\b\344\017,\264") at vfprintf.c:1632
1632    vfprintf.c: No such file or directory.
(gdb) where
#0  0xb7c50383 in _IO_vfprintf_internal (s=0xbfff03a0, format=<optimized out>, ap=0xbfff08a8 "\300\062}\b\344\017,\264") at vfprintf.c:1632
#1  0xb7c6c659 in __IO_vsprintf (string=0xbfff048c "SELECT user_id FROM stats WHERE user_id = ' pass = 'A94A8FE5CCB19BA61C4C0873D391E987982FBBD3'", format=0xb449918c "SELECT user_id FROM stats WHERE user_id = '%s'",
    args=0xbfff08a4 "\001") at iovsprintf.c:42
#2  0xb42bb7da in sqliteSelectUserID () from /root/jka/clanmod/jampgamei386.so
#3  0xb42c1208 in cmLogin () from /root/jka/clanmod/jampgamei386.so
#4  0xb42ca73c in ClientCommand () from /root/jka/clanmod/jampgamei386.so
#5  0xb42f18fe in vmMain () from /root/jka/clanmod/jampgamei386.so
#6  0x08080b71 in VM_Call (vm=0x87c4efc, callnum=6, arg0=0, arg1=0, arg2=0, arg3=0, arg4=0, arg5=0, arg6=0, arg7=0, arg8=0, arg9=0, arg10=0, arg11=0) at /root/openjk/codemp/qcommon/vm.cpp:293
#7  0x080c2bdb in GVM_ClientCommand (clientNum=0) at /root/openjk/codemp/server/sv_gameapi.cpp:102
#8  0x080b9d30 in SV_ExecuteClientCommand (cl=0xb77be01c, s=0x82c2fa0 <MSG_ReadString(msg_s*)::string> "cmlogin test", clientOK=qtrue) at /root/openjk/codemp/server/sv_client.cpp:1295
#9  0x080b9ec9 in SV_ClientCommand (cl=0xb77be01c, msg=0xbfff303c) at /root/openjk/codemp/server/sv_client.cpp:1355
#10 0x080ba51f in SV_ExecuteClientMessage (cl=0xb77be01c, msg=0xbfff303c) at /root/openjk/codemp/server/sv_client.cpp:1588
#11 0x080be023 in SV_PacketEvent (from=..., msg=0xbfff303c) at /root/openjk/codemp/server/sv_main.cpp:834
#12 0x0805c1a5 in Com_RunAndTimeServerPacket (evFrom=0xbfff305c, buf=0xbfff303c) at /root/openjk/codemp/qcommon/common.cpp:849
#13 0x080728bc in NET_Event (fdr=0xbffff0ac) at /root/openjk/codemp/qcommon/net_ip.cpp:1026
#14 0x08072a6a in NET_Sleep (msec=24) at /root/openjk/codemp/qcommon/net_ip.cpp:1075
#15 0x0805d25d in Com_Frame () at /root/openjk/codemp/qcommon/common.cpp:1524
#16 0x0810964b in main (argc=6, argv=0xbffff694) at /root/openjk/shared/sys/sys_main.cpp:812
```

**Comment by ineedblood** [comment]
previous crash fixed on https://github.com/erfg12/clanmod-jka/commit/1c4aaeaefd663bc7a8538489c556c4d431f9631e 

new crash: once logged into the system, dying gets the server crashing / killing also crashes the server 
```
Kill: 0 1 3: jedi killed Reborn by MOD_SABER
]
Program received signal SIGSEGV, Segmentation fault.
0xb42d2c2f in player_die () from /root/jka/clanmod/jampgamei386.so
(gdb) where
#0  0xb42d2c2f in player_die () from /root/jka/clanmod/jampgamei386.so
#1  0xb42daf9d in G_Damage () from /root/jka/clanmod/jampgamei386.so
#2  0xb43d8246 in WP_SaberApplyDamage () from /root/jka/clanmod/jampgamei386.so
#3  0xb43eaa87 in WP_SaberPositionUpdate () from /root/jka/clanmod/jampgamei386.so
#4  0xb42f9ae2 in G_RunFrame () from /root/jka/clanmod/jampgamei386.so
#5  0xb42f1916 in vmMain () from /root/jka/clanmod/jampgamei386.so
#6  0x08080b71 in VM_Call (vm=0x87c4f24, callnum=8, arg0=135400, arg1=0, arg2=0, arg3=0, arg4=0, arg5=0, arg6=0, arg7=0, arg8=0, arg9=0, arg10=0, arg11=0) at /root/openjk/codemp/qcommon/vm.cpp:293
#7  0x080c2d54 in GVM_RunFrame (levelTime=135400) at /root/openjk/codemp/server/sv_gameapi.cpp:122
#8  0x080bed3e in SV_Frame (msec=25) at /root/openjk/codemp/server/sv_main.cpp:1233
#9  0x0805d2e6 in Com_Frame () at /root/openjk/codemp/qcommon/common.cpp:1545
#10 0x0810964b in main (argc=6, argv=0xbffff694) at /root/openjk/shared/sys/sys_main.cpp:812
(gdb) list
723             Q_strncpyz(cwd, Sys_Dirname(cwd), sizeof(cwd));
724             return cwd;
725     }
726     #endif
727
728     #ifndef DEFAULT_BASEDIR
729     #       ifdef MACOS_X
730     #               define DEFAULT_BASEDIR Sys_StripAppBundle(Sys_BinaryPath())
731     #       else
732     #               define DEFAULT_BASEDIR Sys_BinaryPath()

```

**Comment by ineedblood** [comment]
Crashes on client disconnect after being logged in 

```bash
0xb7c3c11b in __GI_____strtol_l_internal (nptr=0x1 <error: Cannot access memory at address 0x1>,
    endptr=0x0, base=10, group=0, loc=0xb7dbec20 <_nl_global_locale>) at strtol_l.c:293
293     strtol_l.c: No such file or directory.
(gdb) where
#0  0xb7c3c11b in __GI_____strtol_l_internal (
    nptr=0x1 <error: Cannot access memory at address 0x1>, endptr=0x0, base=10, group=0,
    loc=0xb7dbec20 <_nl_global_locale>) at strtol_l.c:293
#1  0xb7c3bf20 in __strtol (nptr=0x1 <error: Cannot access memory at address 0x1>, endptr=0x0,
    base=10) at strtol.c:106
#2  0xb7c39260 in atoi (nptr=0x1 <error: Cannot access memory at address 0x1>) at atoi.c:27
#3  0xb42bbcd2 in updateStats (ent=0xb4b255e0 <g_entities>) at g_cmds.c:459
#4  0xb42ba6cc in ClientDisconnect (clientNum=0) at g_client.c:5761
#5  0xb42f18d8 in vmMain (command=5, arg0=0, arg1=0, arg2=0, arg3=0, arg4=0, arg5=0, arg6=0,
    arg7=0, arg8=0, arg9=0, arg10=0, arg11=0) at g_main.c:1060
#6  0x08080b71 in VM_Call (vm=0x87c4ef4, callnum=5, arg0=0, arg1=0, arg2=0, arg3=0, arg4=0,
    arg5=0, arg6=0, arg7=0, arg8=0, arg9=0, arg10=0, arg11=0)
    at /root/openjk/codemp/qcommon/vm.cpp:293
#7  0x080c2b24 in GVM_ClientDisconnect (clientNum=0)
    at /root/openjk/codemp/server/sv_gameapi.cpp:92
#8  0x080b7f1b in SV_DropClient (drop=0xb77be01c,
    reason=0x8302600 <SV_GetStringEdString(char*, char*)::text> "@@@DISCONNECTED")
    at /root/openjk/codemp/server/sv_client.cpp:394
#9  0x080b9274 in SV_Disconnect_f (cl=0xb77be01c) at /root/openjk/codemp/server/sv_client.cpp:951
#10 0x080b9c77 in SV_ExecuteClientCommand (cl=0xb77be01c,
    s=0x82c2fa0 <MSG_ReadString(msg_s*)::string> "disconnect", clientOK=qtrue)
    at /root/openjk/codemp/server/sv_client.cpp:1278
#11 0x080b9ec9 in SV_ClientCommand (cl=0xb77be01c, msg=0xbfff303c)
    at /root/openjk/codemp/server/sv_client.cpp:1355
#12 0x080ba51f in SV_ExecuteClientMessage (cl=0xb77be01c, msg=0xbfff303c)
    at /root/openjk/codemp/server/sv_client.cpp:1588
#13 0x080be023 in SV_PacketEvent (from=..., msg=0xbfff303c)
    at /root/openjk/codemp/server/sv_main.cpp:834
#14 0x0805c1a5 in Com_RunAndTimeServerPacket (evFrom=0xbfff305c, buf=0xbfff303c)
    at /root/openjk/codemp/qcommon/common.cpp:849
#15 0x080728bc in NET_Event (fdr=0xbffff0ac) at /root/openjk/codemp/qcommon/net_ip.cpp:1026
#16 0x08072a6a in NET_Sleep (msec=24) at /root/openjk/codemp/qcommon/net_ip.cpp:1075
#17 0x0805d25d in Com_Frame () at /root/openjk/codemp/qcommon/common.cpp:1524

```

**Comment by ineedblood** [comment]
Code related to the crash 
```c
 459         sqliteUpdateStats("UPDATE stats SET kills=kills+%i, deaths=deaths+%i, duel_wins=duel_wins+%i, duel_loses=duel_loses+%i, flag_captures=flag_captures+%i, ffa_wins=ffa_wins+%i, ffa_loses=ffa_loses+%i, tdm_wins=tdm_wins+%i, tdm_     loses=tdm_loses+%i, siege_wins=siege_wins+%i, siege_loses=siege_loses+%i, ctf_wins=ctf_wins+%i, ctf_loses=ctf_loses+%i WHERE user_id = '%i'", ent->client->pers.sql_kills, ent->client->pers.sql_deaths, ent->client->pers.sql_duelwins,      ent->client->pers.sql_duelloses, ent->client->pers.sql_flagcaps, ent->client->pers.sql_ffawins, ent->client->pers.sql_ffaloses, ent->client->pers.sql_tdmwins, ent->client->pers.sql_tdmloses, ent->client->pers.sql_siegewins, ent->cl     ient->pers.sql_siegeloses, ent->client->pers.sql_ctfwins, ent->client->pers.sql_ctfloses, atoi(ent->client->pers.userID));
```
